In [4]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
vec1 = np.random.rand(1,6)
vec1

array([[0.07881366, 0.29799024, 0.46988129, 0.05252708, 0.58458646,
        0.13242137]])

In [19]:
vec2 = np.random.rand(10,13)
vec2

array([[7.10701464e-01, 3.58878107e-01, 5.90569716e-01, 9.54690241e-02,
        9.92899691e-01, 3.97544260e-01, 8.62830270e-01, 2.29090677e-01,
        7.67976281e-01, 8.77904065e-01, 6.36545860e-01, 6.11500480e-01,
        2.05171416e-01],
       [1.07440103e-01, 5.93043249e-01, 1.90611836e-02, 9.66876101e-01,
        2.96618365e-01, 6.61050855e-01, 5.68355299e-01, 5.78137618e-01,
        4.49907673e-02, 8.27845385e-01, 8.29323843e-02, 8.02626389e-01,
        7.92203047e-01],
       [6.91681598e-01, 7.94667244e-01, 7.25730420e-01, 6.91154856e-01,
        3.89445321e-01, 8.35381477e-01, 3.12173990e-01, 4.25894490e-01,
        6.67612609e-01, 4.45032608e-01, 5.62909035e-01, 3.27271676e-01,
        2.90734844e-01],
       [6.91772467e-01, 2.46403202e-01, 9.48077019e-01, 9.06829447e-01,
        7.04719362e-01, 3.60900704e-01, 3.04442788e-01, 4.79340274e-01,
        2.99727681e-01, 2.49435781e-01, 6.69097092e-02, 2.58020575e-01,
        9.98030872e-01],
       [6.45452898e-01, 1.36766366e-

In [42]:
len(vec2)

10

In [22]:
# 예시 곡네임 분리
ly_name = vec2[0][0]
ly_name

0.7107014636523518

In [60]:
#가사벡터와 멜로디 벡터 분리
lyrics = vec2[1][1:7]
mel = vec2[1][7:]
lyrics,mel

(array([0.59304325, 0.01906118, 0.9668761 , 0.29661836, 0.66105086,
        0.5683553 ]),
 array([0.57813762, 0.04499077, 0.82784539, 0.08293238, 0.80262639,
        0.79220305]))

In [56]:
np.matmul(lyrics,mel)

1.6717246078003558

In [88]:
#가중합 에시(유저가 임의로 0~1사이의 가중치 선택)
import random
a = random.random()
b = random.random()
def weighted_sum(a,b,vec):
# 예시 곡네임 분리
    fin_vec = np.empty((0,6))
    for i in range(len(vec)):
        ly_name = vec[i][0]

        #가사벡터와 멜로디 벡터 분리
        lyrics = vec[i][1:7]
        mel = vec[i][7:]

        wei_vec = a*lyrics + b*mel
        # wei_vec = wei_vec.reshape(1,6)
        fin_vec = np.vstack((fin_vec,wei_vec))
    return ly_name,fin_vec
name, vectors = weighted_sum(a,b,vec2)

In [90]:
vectors.shape

(10, 6)

In [96]:
cosine_sim = cosine_similarity(vec1,vectors)
print(cosine_sim)
print(sorted(cosine_sim[0],reverse=True)[:5]) # 나중에는 원본백터(곡 이름) 출력되도록
# sorted_similar_music = sorted(cosine_sim,key=lambda x:x[1],reverse=True)[1:]
print(np.argsort(cosine_sim[0]))

[[0.78893992 0.82631487 0.81421106 0.72653328 0.83086175 0.91732052
  0.83021793 0.83720527 0.77112862 0.84761154]]
[0.9173205222551745, 0.847611537521786, 0.8372052734379748, 0.8308617457218856, 0.8302179345983681]
[3 8 0 2 1 6 4 7 9 5]


In [ ]:
def get_title_from_index(index):
    return df[df.index == index]["title"].values[0]
def get_index_from_title(title):
    return df[df.title == title]["index"].values[0]

movie_user_likes = "Avatar"
movie_index = get_index_from_title(movie_user_likes)
similar_movies = list(enumerate(cosine_sim[movie_index]))

sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)[1:]

i=0
print(movie_user_likes+"와 비슷한 영화 3편은 "+"\n")
for item in sorted_similar_movies:
    print(get_title_from_index(item[0]))
    i=i+1
    if i==3:
        break